### ISSUE TITLE
Last bugs to fix

### ISSUE THREAD

**Issue by kenz097** [kenz097/WorldHappiness2021#2]
Risolvere il problema della tabella principale nella pagina test_query.
risolvere la modifica di un paese aggiustando la grafica e inserendo tutti i valori che mancano, come campi obbligatori solo il nome del paese che un utente vuole modificare.
Inserire che un utente nell'inserimento deve inserire obbligatoriamente tutti i valori indicanti dal form.
Inserire le risposte per le operazioni effettuabili.

**Comment by ogeid97** [comment]
modificata la tabella, aggiunti alert per avvisare l'utente della funzione attivata

**Comment by kenz097** [comment]
all fixed
